name: Cross-Compile TinyCC

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger on

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [linux, windows]
    
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y mingw-w64 build-essential

      - name: Build for Linux
        if: matrix.target == 'linux'
        run: |
          ./configure
          make -j$(nproc)
          tar -czvf tinycc-linux.tar.gz tcc

      - name: Build for Windows
        if: matrix.target == 'windows'
        run: |
          ./configure --cross-prefix=x86_64-w64-mingw32-
          make -j$(nproc)
          zip -r tinycc-windows.zip tcc.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tinycc-${{ matrix.target }}
          path: tinycc-*.*
  
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          repository: Tiny-C-Compiler/mirror-repository
          files: artifacts/tinycc-*/tinycc-*
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          draft: false
