name: Cross-Platform Build and Release

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync repositories
        uses: wei/git-sync@v3
        with:
          source_repo: "https://repo.or.cz/tinycc.git"
          source_branch: "mob"
          destination_repo: "git@github.com:Tiny-C-Compiler/mirror-repository"
          destination_branch: "mob"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  build-binaries:
    needs: git-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mirror repository
        uses: actions/checkout@v4
        with:
          repository: Tiny-C-Compiler/mirror-repository
          ref: mob
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc \
            make \
            gcc-mingw-w64-x86-64 \
            binutils-mingw-w64-x86-64 \
            mingw-w64-x86-64-dev \
            build-essential

      - name: Build Linux binary
        run: |
          ./configure
          make
          mv tcc tcc-linux

      - name: Build Windows binary
        run: |
          # Configure for Windows target with static linking
          ./configure --cross-prefix=x86_64-w64-mingw32- \
            --cpu=x86_64 \
            --extra-cflags="-static" \
            --extra-ldflags="-static" \
            --with-sysroot=/usr/x86_64-w64-mingw32

          # Remove Linux-specific libraries from Makefile
          sed -i 's/-ldl//g' Makefile
          sed -i 's/-lpthread//g' Makefile
          
          make
          mv tcc.exe tcc-windows.exe

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: tcc-linux
          path: tcc-linux

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: tcc-windows.exe
          path: tcc-windows.exe

  create-release:
    needs: build-binaries
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: tcc-linux

      - name: Download Windows binary
        uses: actions/download-artifact@v4
        with:
          name: tcc-windows.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          repository: Tiny-C-Compiler/mirror-repository
          token: ${{ secrets.MIRROR_REPO_TOKEN }}
          tag_name: latest
          overwrite: true
          files: |
            tcc-linux
            tcc-windows.exe
          body: |
            Automated cross-platform build containing:
            - Linux executable (ELF64)
            - Windows executable (PE32+)
            
            Built from mob branch at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
