name: Git Sync

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git credentials for HTTPS
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global credential.helper cache

      - name: Run git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://repo.or.cz/tinycc.git"
          source_branch: "mob"
          destination_repo: "https://github.com/Tiny-C-Compiler/mirror-repository.git"
          destination_branch: "mob"
          token: ${{ secrets.GITHUB_TOKEN }}  # Use a GitHub token for authentication
